name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build the Docker image for Django
      - name: Build Django Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/socialbook:latest -f Dockerfile .

      # Push Django Docker Image to Docker Hub
      - name: Push Django Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/socialbook:latest